name: Trivy vulnerability scan

on:
  schedule:
    # Scan the image regularly (once a day)
    - cron: '45 03 * * *'
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  pull-requests: write
  security-events: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "poland-tf/${{ github.event.repository.name }}"

jobs:
  build:
    name: Scan current image & report results
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: "os"
          timeout: '15m0s'
        env:
          TRIVY_USERNAME: ${{ secrets.GH_LOGIN }}
          TRIVY_PASSWORD: ${{ secrets.GH_ACCESS }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'